### ISSUE TITLE
error train_ibt.py 

### ISSUE THREAD

**Issue by ddehun** [laihuiyuan/Generic-resources-for-TST#3]
HI! I hope to ask for your help when I run your code.

When I run 'train_ibt.py', I meet the following error.

  ```
File "train_ibt.py", line 203, in <module>
    main()
  File "train_ibt.py", line 141, in main
    out0 = model[A].decode(srcs, mask, opt.max_len, False)
  File "/home/nas2_userG/chaehunpark/codes/generic-resources-for-tst/model.py", line 56, in decode
    model_inputs = self.prepare_inputs_for_generation(
TypeError: prepare_inputs_for_generation() takes 2 positional arguments but 4 were given
```

My transformers version is 2.5.1 as written in README.md.

It seems that the problem is due to the misaligned number of arguments.
Could you give me some advice on this error?
Thank you!

**Comment by laihuiyuan** [comment]
Hi! Thanks for your interest in our work. 

I think this is because huggingface updated the codes a little bit. The code of BART is from transformers since I wanted to know all the details in the implementation. Yeah, I just found that the return of BART decoder has been updated (maybe more?). 

I have reset the code to the previous version and it should work fine now.
